- DistanceLimitDataPointsFilter:
      dist: 20
      removeInside: 0

- CompressionDataPointsFilter:
      knn: 10
      maxDist: 0.3
      maxDeviation: 10
      maxVolumeRatio: 2.0
      maxIterationCount: 1000
      initialVariance: 9e-4
      keepNormals: 1
      keepEigenValues: 1
      keepEigenVectors: 1
      sortEigen: 0

- OrientNormalsDataPointsFilter

- CutAtDescriptorThresholdDataPointsFilter:
      descName: probabilityDynamic
      useLargerThan: 1
      threshold: 0.8
