- DistanceLimitDataPointsFilter:
      dist: 20
      removeInside: 0

- CompressionDataPointsFilter:
      knn: 10
      maxDist: 0.3
      maxDeviation: 0.1
      epsilon: 0
      maxIterationCount: 1
      maxVolumeRatio: inf
      keepNormals: 1
      keepEigenValues: 1
      keepEigenVectors: 1

- OrientNormalsDataPointsFilter

- CutAtDescriptorThresholdDataPointsFilter:
      descName: probabilityDynamic
      useLargerThan: 1
      threshold: 0.8
